### ISSUE TITLE
Changes to logo

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/reveal-ucb-theme#1]
It is a great piece of information to include, but is not the most important thing so I think it should be in the footer.

I found CSS SVG way to do it that you might consider as well. 
```
body.reveal-viewport {
    background-image: url(ucb-white.svg);
    background-size: 20%;
    background-repeat: no-repeat;
    background-position: 3% 96%;
}
```
I don't think it works well for print yet, but it has the added benefit of working offline

**Comment by brookestevens** [comment]
Added logo to the footer. I also used an <img> tag instead of css because the CSS breaks if the site is served out of a subdirectory
